### ISSUE TITLE
Like Clockwork *New Game*

### ISSUE THREAD

**Issue by filrod** [filrod/MISC_public#5]
## Make a new game | Theme: Like Clockwork
It will be a racer!

# TODO:

- [x] Make one track

- [x] Make a car to race with in blender

- [x] Make scripts for car controls

- [x] Make a UI with a timer, laps and pause

- [x] Add in Music from Lisa Lorenzino
